steps:
  # ── Bước 1: Chạy Unit Tests ───────────────────────────────
  - name: "python:3.11-slim"
    id: test
    entrypoint: "bash"
    args:
      - "-c"
      - "pip install -r requirements.txt -q && pytest tests/ -v --tb=short"
    env:
      - "ENVIRONMENT=test"

  # ── Bước 2: Build Docker Image ────────────────────────────
  - name: "gcr.io/cloud-builders/docker"
    id: build
    args:
      - "build"
      - "--build-arg=APP_VERSION=$_VERSION"
      - "-t"
      - "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_SERVICE:$_VERSION"
      - "-t"
      - "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_SERVICE:latest"
      - "."
    waitFor: ["test"]

  # ── Bước 3: Push lên Artifact Registry ───────────────────
  - name: "gcr.io/cloud-builders/docker"
    id: push
    args:
      - "push"
      - "--all-tags"
      - "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_SERVICE"
    waitFor: ["build"]

  # ── Bước 4: Deploy lên Cloud Run ─────────────────────────
  - name: "gcr.io/cloud-builders/gcloud"
    id: deploy
    args:
      - "run"
      - "deploy"
      - "$_SERVICE"
      - "--image=$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_SERVICE:$_VERSION"
      - "--region=$_REGION"
      - "--platform=managed"
      - "--allow-unauthenticated"
      - "--set-env-vars=APP_VERSION=$_VERSION,ENVIRONMENT=production"
      - "--memory=512Mi"
      - "--cpu=1"
      - "--min-instances=0"
      - "--max-instances=10"
      - "--quiet"
    waitFor: ["push"]

  # ── Bước 5: Ghi deployment log vào GCS Bucket ────────────
  - name: "gcr.io/cloud-builders/gcloud"
    id: log
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo '{"version":"$_VERSION","service":"$_SERVICE","status":"success"}' \
          | gsutil cp - gs://$_BUCKET/deployments/$_VERSION.json
    waitFor: ["deploy"]

# ── THIẾT LẬP BIẾN SUBSTITUTIONS (MẶC ĐỊNH) ────────────────
substitutions:
  _REGION: "asia-southeast1"
  _REPO_NAME: "myapp-repo"
  _SERVICE: "my-app"
  _BUCKET: "myapp-artifacts-terraform-gcp-450004"
  _VERSION: "latest"

images:
  - "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_SERVICE:$_VERSION"
  - "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_SERVICE:latest"

timeout: "900s"
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_MEDIUM"
